### ISSUE TITLE
Missing category: Distillery

### ISSUE THREAD

**Issue by MatthieuOSM** [caresteouvert/caresteouvert#750]
**Name**: Distillery (FR = Distillerie)
**Tagging**: craft=distillery (https://wiki.openstreetmap.org/wiki/Tag:craft%3Ddistillery)
**Country**: France
**Example in OpenStreetMap**: https://www.openstreetmap.org/node/7329333050
**Example in "Ca reste ouvert"**: https://www.caresteouvert.fr/@45.598010,-0.056740,19.00
**Icon**: I'm not sure this exists, nor in OSM layout system.

I've been contacted by a tourism agency to add more POI regarding tourism and leisure activities among that one. Some of the distillery establishments in my territory seem to be open for spirits tasting.

**Comment by overflorian** [comment]
C'est fait depuis 21j
