### ISSUE TITLE
Missing category: Key cutter

### ISSUE THREAD

**Issue by pyrog** [caresteouvert/caresteouvert#797]
**Name**: key cutter

**Tagging**: `craft=key_cutter`

**Country**: France…

**Example in OpenStreetMap**: https://www.openstreetmap.org/node/7416535732

**Example in "Ca reste ouvert"**: https://www.caresteouvert.fr/@46.674179,5.541226,19.57

**Icon**: https://fontawesome.com/icons/key?style=solid

More than [2 451](https://taginfo.openstreetmap.org/tags/craft=key_cutter) objects in OSM.
See #558

**Comment by PanierAvide** [comment]
Done, see #870
