### ISSUE TITLE
Missing category: shoemaker

### ISSUE THREAD

**Issue by pyrog** [caresteouvert/caresteouvert#799]
**Name**: shoemaker

**Tagging**: craft=shoemaker

**Country**: France…

**Example in OpenStreetMap**: https://www.openstreetmap.org/node/7556203993

**Example in "Ca reste ouvert"**: https://www.caresteouvert.fr/@45.749650,4.848140,19.57

**Icon**: 

More than [7 988](https://taginfo.openstreetmap.org/tags/craft=shoemaker) objects in OSM.
See #558

**Comment by PanierAvide** [comment]
Done, see #870
