### ISSUE TITLE
Ré-ouvrir le service pour le 2nd confinement en France

### ISSUE THREAD

**Issue by overflorian** [caresteouvert/caresteouvert#829]
Rouvrons le service !
Dans un premier temps, afin de le tester avant réouverture complète, faisons un premier test centré sur Lyon :
- [X] Ouvrir un serveur
- [x] Importer les données pour la France (dont territoires d'Outre-mer)
- [x] Installer le service
- [x] Configurer le serveur de tuiles
- [x] Réactiver le service de géo-coding / barre de recherche (via l'API de Jawg Maps ?)
- [x] [Ouvrir le service sur la ville de Lyon](https://github.com/caresteouvert/caresteouvert/issues)
- [x] Changer la page d'accueil de caresteouvert.fr
Je propose de remplacer "Ça reste ouvert is now closed! Thanks to all contributors, partners and visitors. Wear a mask, wash your hands or see you soon." par "Ça reste ouvert sera bientôt de retour ! Vous recherchez une solution de promotion des commerces de votre territoire, [contactez-nous](mailto:florian@caresteouvert.fr)."

**Comment by vinber** [comment]
promotion "durable"
Sur cette page, peut-on faire un clin d'oeil à OpenStreetMap ? (fièrement basé sur des données OSM ? ou un truc du genre ?)
il me semble que cela doit s'affirmer, sans prendre le pas sur la communication habiutuelle ! et peut-être que cela peut-être entenu même :)

**Comment by overflorian** [comment]
De quelle page parles-tu @vinber ?
Pour rappel on fait déjà mention d'OSM sur la carte, dans la page /à propos et aussi en bas de chaque POI :
![7  Lieu disposant déjà de détails](https://user-images.githubusercontent.com/11553211/98581544-ede25e00-22c1-11eb-802a-737b26a4c5c4.jpg)

**Comment by vinber** [comment]
> De quelle page parles-tu @vinber ?

phrase que tu cites : Ça reste ouvert sera bientôt de retour ! Vous recherchez une solution de promotion des commerces de votre territoire, contactez-nous."

l'actuelle page https://www.caresteouvert.fr/

**Comment by overflorian** [comment]
Ah ok, d'accord. Oui je pense que c'est une bonne idée de faire ça.

**Comment by overflorian** [comment]
Wording de la page d'accueil :

Ça reste ouvert sera bientôt de retour ! Vous recherchez une solution de promotion durable des commerces de votre territoire, [contactez-nous](mailto:contact@caresteouvert.fr).
Fièrement basé sur les données d'[OpenStreetMap](https://openstreetmap.org)
