### ISSUE TITLE
les icones n'arrivent pas en même temps

### ISSUE THREAD

**Issue by vinber** [caresteouvert/caresteouvert#831]
Quand on zoome, ce moment de mélange entre rond avec icone et rond blanc à l'intérieur est surprenant.

![Capture d’écran de 2020-11-10 16-28-21](https://user-images.githubusercontent.com/890869/98694576-e8445100-2371-11eb-903c-fc83e0da85ca.png)

Cela apparait ensuite quand on zoome de nouveau

**Comment by overflorian** [comment]
Je ne suis pas certain de comprendre ce dont tu parles. Est-ce le fait que les icônes ne s'affichent pas tout le temps ? Comme dans ton exemple pour le POI juste à droite de la poissonnerie "le grand large" ?
Si c'est bien de cela dont tu parles, je ne suis personnellement pas choqué : l'affichage des icônes est dynamique et très dépendant du niveau de zoom. Je crois que c'est un choix technique avant tout. Mais peut-être que je me trompe.

**Comment by frodrigo** [comment]
L'icone et le texte ne font qu'un seul bloc et ne sont affiché que s'il y a la place. Le texte pourrait être passé en optionnel dans le style.

**Comment by overflorian** [comment]
Tu veux faire des tests @frodrigo ? A toi de voir si ça donne quelque chose. Le sujet ne me paraît vraiment pas urgent

**Comment by frodrigo** [comment]
on peut avoir un peu plus d'icones.

![optional](https://user-images.githubusercontent.com/1785486/98715340-4c730f00-238a-11eb-868d-f695055c5850.gif)

**Comment by frodrigo** [comment]
Done.

**Comment by overflorian** [comment]
Je suis moyennement convaincu du résultat en zone dense (ici, Bordeaux) :
![image](https://user-images.githubusercontent.com/11553211/98792124-520e3a80-2406-11eb-88f8-5c57d609db8a.png)

ça fait un peu un effet "confettis" : l'interface est saturée.
Ne devrait-on pas afficher un nombre maximum de POIs dans une bbox donnée ? Bon, pour la priorisation de l'affichage, c'est un peu tricky : on ne veut pas, je pense, favoriser l'affichage en fonction de la couleur (vert/rouge/gris). Peut-être favoriser une répartition plus ou moins homogène sur l'ensemble de l'écran ?

**Comment by frodrigo** [comment]
> ça fait un peu un effet "confettis" : l'interface est saturée

Ta remarque est liée aux icones ou aux cercles ?

Je n'ai touché qu'au icones pour avoir moins de cercles vides.

**Comment by overflorian** [comment]
Ma remarque est liée à la combinaison d'un trop grand nombre de cercles avec icônes. Mon impression personnelle est que cela produit un carte "brouillon", et je comprends pourquoi on avait l'ancienne configuration. C'était un bon compromis créé dans l'urgence, maintenant on peut prendre le temps d'affiner l'affichage maintenant.

**Comment by vinber** [comment]
sans aucune forme de d'urgence / donner la priorité aux cercles verts et leurs remplissages par les icones -> services ouverts et fonctionnels

**Comment by overflorian** [comment]
J'aime bien l'idée. J'imagine que cela demande une configuration un peu fine et intelligente qui ne soit pas juste on/off.
On priorise déjà l'affichage des points verts selon les niveaux de zoom donc c'est dans la continuité.

**Comment by overflorian** [comment]
Hello, je réactive cette discussion car depuis que l'on affiche presque tous les lieux en vert (sauf restaurants et bars), l’interface me paraît illisible sur les zones denses :
![image](https://user-images.githubusercontent.com/11553211/102330003-52f83600-3f89-11eb-9db9-711e96f70583.png)

![image](https://user-images.githubusercontent.com/11553211/102330048-62777f00-3f89-11eb-9b78-92d4e92fac8d.png)

**Solutions possibles**
- Limiter le nombre de POI affichés. C'est le choix qu'à fait Google Maps, donc les gens sont habitués à ce genre de comportement. Mais cela risque de laisser à penser qu'il manque des POIs. Si c'est mal géré, c'est un vrai problème (cf. le résultat _controversé_ dans Maps.Me)
- afficher les bâtiments "commerciaux" d'une couleur différente, comme dans Google Maps encore une fois. 
_Je sais que techniquement c'est la merde, qu'il faut bidouiller le fond de carte vecto, et qu'en plus il vaudra identifier les bâtiments indirectement via la présence d'un point commercial à l'intérieur de leur périmètre ... Ou alors, solution intermédiaire, on n'affiche que les _building=commercial_ mais cela exclu tous le commerces au rdc d'un immeuble ..._
Pour moi c'est la rolls des solutions : on indique visuellement qu'un POI va apparaître si utilisateur continue de zoomer à cet endroit sans surcharger la carte.
- Prioriser l'affichage des lieux "confirmés ouverts" dans les données. C'est à dire uniquement les lieux pour lesquels il y a vraiment les tags, et non pas TOUS les lieux affichés en vert.
A défaut, on peut imaginer afficher en plus petit les lieux "non confirmés", comme aujourd'hui pour les points gris.
- Prioriser l'affichage par type de POI (par exemple les grandes surface apparaîtraient en premier, mais bon, on va sûrement arriver à des choix très discutables)
- faire un mix de ces solutions ? pour rappel le problème ne se présente que sur les zones denses donc éviter de péter le rendu sur les villages et petites villes.

**Comment by frodrigo** [comment]
1) Sur les zooms faibles passer les points sous le texte, et couleurs plus pales.
2) En zone dense faire deux couches la couleur de pourtour et le blanc pour ne pas faire cet effet d'entassement.

**Comment by frodrigo** [comment]
Amélioration en ligne.
