### ISSUE TITLE
Retirer la question de disponibilité des masques

### ISSUE THREAD

**Issue by vinber** [caresteouvert/caresteouvert#832]
Par exemple sur ce point : https://prod-caresteouvert.makina-corpus.net/@44.769188,-0.578277,19.09/place/n7271723165

Je ne pense pas que la question du masque soit encore d'actualité.

**Comment by overflorian** [comment]
Pareil pour le gel hydroalcoolique. Dans mes souvenirs, cela s'applique aux pharmacies uniquement.

**Comment by frodrigo** [comment]
All done.
(en attente des droits pour fermer les issues)
