### ISSUE TITLE
Les crèches sont ouvertes

### ISSUE THREAD

**Issue by vinber** [caresteouvert/caresteouvert#833]
Retirer les crèches de la liste des établisssements potentiellement ouvert : exemple : https://prod-caresteouvert.makina-corpus.net/@44.769928,-0.583197,16.37/place/n6135339556

"Les crèches, écoles, collèges et lycées restent ouverts avec un protocole sanitaire renforcé dont le port du masque obligatoire dès l’âge de 6 ans." https://www.gouvernement.fr/info-coronavirus/confinement

**Comment by frodrigo** [comment]
Il faut passer en revue ces CSV
https://github.com/PanierAvide/Covid_enseignes

**Comment by vinber** [comment]
Ok, donc si je comprend bien il faut :

- déterminer la "catégory"
- ajouter la category_osm

@overflorian sais tu où on trouve cette catégorie pour ajouter amenity=kindergarten

**Comment by frodrigo** [comment]
Ça fait référence à ça https://github.com/caresteouvert/caresteouvert/blob/master/categories.json

**Comment by vinber** [comment]
ok, 2 questions encore :

- est ce la bonne façon de faire : https://github.com/caresteouvert/Covid_enseignes/pulls
- ne dervait-on pas "rapatrier" ce dépot de code dans ca reste ouvert ? @PanierAvide @frodrigo vos avis ?

**Comment by frodrigo** [comment]
Ton PR ne va rien changer seul les closed du ficher sont utilisés.
