### ISSUE TITLE
Supprimer la catégorie "Tabac & alcool"

### ISSUE THREAD

**Issue by overflorian** [caresteouvert/caresteouvert#834]
La catégorie "tabac et alcool" avait un sens durant le premier confinement pour mettre en avant ces produits très recherchés, mais pour le 2nd confinement il ne me semble pas nécessaire de les laisser dans une catégorie dédiée.

Je propose donc de virer la catégorie et que :
- Les POIs de la sous-catégorie "alcool" devraient apparaître dans la rubrique "alimentation"
- Les POIs des sous-catégories "e-cigarette" et "tabac" devraient apparaître dans la rubrique "autres établissements

**Comment by frodrigo** [comment]
Done.

**Comment by overflorian** [comment]
merci
