### ISSUE TITLE
Evolution du wording re-confinement

### ISSUE THREAD

**Issue by overflorian** [caresteouvert/caresteouvert#836]
Suite au reconfinement, on devrait re-adapter le wording de plus près (suite à https://github.com/caresteouvert/caresteouvert/issues/728).
Je propose de continuer à utiliser le terme "crise sanitaire" et non pas "confinement" car la situation risque de continuer à évoluer rapidement (couvre-feu, mi-confinement, confinement par intermittence ...)

- "Lieu ouvert durant la crise sanitaire" : OK
- "Lieu ouvert durant la crise sanitaire avec des horaires adaptés" : OK
- "Lieu fermé durant la crise sanitaire" : OK
- la phrase "Lieu potentiellement ouvert durant la crise sanitaire pour proposer ses services habituels ou de nouveaux. Ouvert ou fermé ? À vous de le dire." ne me paraît pas claire ; je propose de la remplacer par une phrase plus simple "Lieu potentiellement ouvert durant la crise sanitaire. Ouvert ou fermé ? À vous de le dire."
- "Ceci est votre établissement ou celui de votre groupe ? Gagnez en visibilité après le confinement" -> "Ceci est votre établissement ou celui de votre groupe ? Gagnez en visibilité durant la crise sanitaire"

J'ai aussi changé le wording sur la page https://github.com/caresteouvert/caresteouvert/edit/master/README.md pour prendre en compte le changement d'URL du dépôt.

J'oublie quelque chose ?

**Comment by vinber** [comment]
"Lieu potentiellement ouvert durant la crise sanitaire. Ouvert ou fermé ? À vous de le dire."
Lieu vraisemblablement fermé à l'accueil durant la crise sanitaire mais pouvant proposer des services ! À vous de le dire.

c'est un test de "wording" car on va surtout "parler des services" je pense
