### ISSUE TITLE
Argent

### ISSUE THREAD

**Issue by pyrog** [caresteouvert/caresteouvert#837]
Le libellé "Argent" ne distingue pas une banque d'un DAB.
Il convient pour la catégorie, mais pas du tout pout l'affichage d'un POI.

Afficher plutôt :

- Distributeur de billets
- Banque

Dans la même idée, l'icône ne fait pas la distinction non plus.

[Banque](https://prod-caresteouvert.makina-corpus.net/@46.673160,5.551660,18.29/place/n6843905399) | [DAB](https://prod-caresteouvert.makina-corpus.net/amenity%2Fmoney@46.672869,5.551587,20.29/place/n1082774375)
--|--
<img alt="Banque" src="https://user-images.githubusercontent.com/2158081/98794832-cc8c8980-2409-11eb-9531-84b94d4f1c9c.png"> | <img  alt="DAB" src="https://user-images.githubusercontent.com/2158081/98795853-01e5a700-240b-11eb-9f7c-fb9fe7dfe701.png">

PS: ce DAB à le tag operator qui pourrait afficher la banque (et son logo) dont il dépend (cf. #838)

**Comment by overflorian** [comment]
Je comprends pourquoi tu veux faire ça d'une manière absolue mais a-t-on vraiment besoin d'aller autant dans le détail ? Si le libellé "argent est compréhensible", pourquoi faire a distinction ?

**Comment by overflorian** [comment]
Autres suggestion : virer carrément les distributeurs de billets. Ne laisser qu'une catégorie renommée "banque"

**Comment by pyrog** [comment]
Le pékin moyen va utiliser CRO pour chercher une banque ouverte,
et puis une autre pour les distributeurs de billets,
une autre pour …

Je propose de virer toutes les catégories, ça sera plus simple à coder 😆

**Comment by overflorian** [comment]
Les distributeurs ne sont maintenant plus affichés, je ferme ce bug
