### ISSUE TITLE
Missing category: (name of category)

### ISSUE THREAD

**Issue by AromoLaCave** [caresteouvert/caresteouvert#839]
Caviste

**Tagging**: (tagging of category)

**Country**: (country of category)
France

**Example in OpenStreetMap**: (link starting with https://www.openstreetmap.org/node/...)
https://www.openstreetmap.org/changeset/84930652

**Example in "Ca reste ouvert"**: (link starting with https://www.caresteouvert.fr/...)
https://lyon.caresteouvert.fr/other@45.758394,4.836852,12.00/place/n5849790141

**Icon**: (link starting with https://github.com/gravitystorm/openstreetmap-carto/blob/master/symbols/...)

**Comment by overflorian** [comment]
je ferme car cette suggestion est en doublon avec https://github.com/caresteouvert/caresteouvert/issues/840
