### ISSUE TITLE
caviste

### ISSUE THREAD

**Issue by cavecharlemagne** [caresteouvert/caresteouvert#840]
**Name**: (name of category)

**Tagging**: (tagging of category)

**Country**: (country of category)

**Example in OpenStreetMap**: (link starting with https://www.openstreetmap.org/node/...)

**Example in "Ca reste ouvert"**: (link starting with https://www.caresteouvert.fr/...)

**Icon**: (link starting with https://github.com/gravitystorm/openstreetmap-carto/blob/master/symbols/...)

**Comment by PanierAvide** [comment]
Done, see #870
