### ISSUE TITLE
Permettre de filtrer le click&collect (et plus) dans le menu de filtrage des POIs

### ISSUE THREAD

**Issue by overflorian** [caresteouvert/caresteouvert#842]
Une fois qu'on aura permis de créer de la donnée plus détaillée (https://github.com/caresteouvert/caresteouvert/issues/841) on pourrait permettre de la filtrer.

**Comment by PanierAvide** [comment]
C'est implémenté, et ce sera mis en prod avec le nouveau formulaire

**Comment by PanierAvide** [comment]
En prod
