### ISSUE TITLE
Les filtres "Masques" et "Gel Hydroalcooliques" restent proposés

### ISSUE THREAD

**Issue by nuxper** [caresteouvert/caresteouvert#844]
I believe it was decided to not record whether Masks and Gel can be bought in a shop anymore.

I believe the question is no longer asked in the wizard which I believe is good.
However "Masques" et "Gel Hydroalcooliques" are still available in the filters :

To reproduce : Go to https://lyon.caresteouvert.fr/health@45.747054,4.824491,19.53
Screenshot :
![image](https://user-images.githubusercontent.com/7891262/99150440-e8f02680-2694-11eb-899c-6c2996f269b7.png)

Expected : "Masques" et "Gel Hydroalcooliques" should not be available in the filters 

Observed on windows on Firefox and Chrome + on android firefox

**Comment by overflorian** [comment]
I agree!
