### ISSUE TITLE
Afficher les infos du champ libre sur le POI

### ISSUE THREAD

**Issue by overflorian** [caresteouvert/caresteouvert#847]
Le champ libre proposé en fin de formulaire peut contenir des infos utiles aux utilisateurs.
En outre, il permet de compléter des infos non prévues dans le formulaire.
Affichons-le aux utilisateurs !

## Comportement actuel 
Le champ libre, si rempli, créé une note dans OSM. C'est tout.

## Proposition :
La note est toujours créée (ou pas ??), mais en plus, le contenu du champ libre est ajouté dans osm avec le tag `note:covid19`. La fiche du POI affiche ce tag directement.
Ouvrir le POI affiche le contenu déjà créé dans le champ libre et son formulaire en permet d'édition directe.

**Comment by vinber** [comment]
si c'est pour affichage alors je dirais description:covid19=* plutôt que note:covid19=* ce dernier étant plutôt à destination de la communauté OSM (https://wiki.openstreetmap.org/wiki/COVID-19_-_How_to_Map#Summary_of_main_keys)

**Comment by overflorian** [comment]
Bien joué. Je plussoie.

**Comment by frodrigo** [comment]
En prod.
