### ISSUE TITLE
Coiffeurs / Salons de beauté

### ISSUE THREAD

**Issue by nuxper** [caresteouvert/caresteouvert#848]
**Is your feature request related to a problem? Please describe.**
Les coiffeurs / Salons de beauté / salons de massage devraient-ils être affichés ? Ils ne peuvent pas être ouverts.

**To Reproduce**
https://lyon.caresteouvert.fr/@45.765157,4.836256,19.02/place/n7610317075

Les seules exceptions pourraient être les coiffeurs qui vendent des produits : champoing ... à distance. Mais je n'en ai pas croisé.

**Comment by vinber** [comment]
Bonjour et merci du retour 
sans doute à faire dans legal_rules.csv, je crois que les closed sont pris en compte (https://github.com/caresteouvert/Covid_enseignes/blob/master/legal_rules.csv)
ou rules si on considèrent que ce n'est pas complétement évident car par exemple pour les salons de beauty  : https://www.marionnaud.fr/covid-mesures-reouvertures-magasins

**Comment by nuxper** [comment]
Malheureusement la page que tu indiques date de mai. Les magasins marionnaud sont fermés pour les services salon de beauté + achat en magasin.
La vente de produits de beauté peut rester ouvert en click and collect / en livraison ceci dit.
Si c'est purement de la vente de produit, le magasin devrait plutôt être taggé "shop=cosmetics" mais il est vrai que beaucoup de salons de beauté vendent des cosmétiques et inversement.

**Comment by vinber** [comment]
oups, tu as raison et ma logique aurait pu m'aider !
mais donc cela pose bien la question de comment indiquer que c'est "commerces fermés mais services actifs" et donc de ce clic and collect, order and collect

merci https://github.com/caresteouvert/Covid_enseignes/commit/1aee007714bd754d017096e4211aa62005b038ef

**Comment by overflorian** [comment]
Est-ce que les coiffeurs et salons de massages rouvriront dès ce samedi ? Si tel est le cas, alors on a bien fait de ne pas les enlever et ce bug n'a plus lieu d'être ;)

**Comment by nuxper** [comment]
oui et en plus certains vendaient des produits cosmétiques à distance. Je clos le ticket.
