### ISSUE TITLE
CRO ne modifie pas OSM

### ISSUE THREAD

**Issue by vinber** [caresteouvert/caresteouvert#849]
lorsque je modifie ce point pour dire qu'il est fermé (oui c'est un test sur un coiffeur : https://lyon.caresteouvert.fr/@45.736740,4.829564,18.64/place/n3264698139), alors CRO confirme
![Capture d’écran de 2020-11-16 16-24-38](https://user-images.githubusercontent.com/890869/99272594-423c8f00-2828-11eb-8a88-e75337433a58.png)

30 minutes après cela ne semble avoir rien changé dans OSM : https://www.openstreetmap.org/node/3264698139#map=19/45.73694/4.82957&layers=N

**Comment by vinber** [comment]
Dernière modification d'OSM, vendredi dernier : https://www.openstreetmap.org/changeset/94049108#map=12/45.8033/4.8355

**Comment by frodrigo** [comment]
Je viens de le relancer. Upload des changes set en cours.
Ça tournait tjs, pas d'erreur, mais visiblement ça ne marchait pas.

**Comment by vinber** [comment]
cela veut dire que les changesets depuis vendredi vont remonter ?

**Comment by frodrigo** [comment]
Les données oui, mais les changesets tous daté de maintement.

**Comment by vinber** [comment]
ok, c'est arrivé je ferme (et si c'est pas comme cela qu'il faut faire tu rouvres :) )
