### ISSUE TITLE
Missing category: (name of category)

### ISSUE THREAD

**Issue by Lebosquetfleurs** [caresteouvert/caresteouvert#852]
**Name**: (name of category)

**Tagging**: (tagging of category)

**Country**: (country of category)

**Example in OpenStreetMap**: (link starting with https://www.openstreetmap.org/node/...)

**Example in "Ca reste ouvert"**: (link starting with https://www.caresteouvert.fr/...)

**Icon**: (link starting with https://github.com/gravitystorm/openstreetmap-carto/blob/master/symbols/...)

**Comment by vinber** [comment]
Bonjour,
Github est parfois complexe, pouvez vous nous dire qu'elle est le souci que vous rencontrez ?

**Comment by frodrigo** [comment]
https://lebosquet-fleurs.fr/ à Lyon

**Comment by Lebosquetfleurs** [comment]
Bonjour, 

Je n’arrive pas à ajouter mon atelier afin que les habitants du quartier puissent être au courant que je propose des livraisons de fleurs à vélo et du click’n’collect.

Bien à vous.

Anaïs Bouzar, fondatrice 
Contact : 06 08 89 93 24
Instagram : lebosquet.fleurs
Site internet : https://lebosquet-fleurs.fr




De : Frédéric Rodrigo
Envoyé le :mercredi 18 novembre 2020 17:53
À : caresteouvert/caresteouvert
Cc : Lebosquetfleurs; Author
Objet :Re: [caresteouvert/caresteouvert] Missing category: (name ofcategory) (#852)

https://lebosquet-fleurs.fr/ à Lyon
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.



-- 
L'absence de virus dans ce courrier électronique a été vérifiée par le logiciel antivirus Avast.
https://www.avast.com/antivirus

**Comment by vinber** [comment]
ok, je l'ajoute, cela prend quelques minutes et vous devriez le trouver (vouspouvez nous le confirmer ici pour fermer cette "issue"

**Comment by vinber** [comment]
il est ici https://lyon.caresteouvert.fr/@45.751428,4.843031,19.11/place/n8142127733
