### ISSUE TITLE
Pourquoi cela ne remonte pas ?

### ISSUE THREAD

**Issue by vinber** [caresteouvert/caresteouvert#853]
ce point https://www.openstreetmap.org/node/8142127733#map=19/45.75139/4.84323

on devrait l'avoir ici : https://lyon.caresteouvert.fr/@45.751562,4.842909,18.79

Les fleuristes remontent bien : https://lyon.caresteouvert.fr/@45.750787,4.848377,19.19/place/n2243036388

Je suis trop impatient ?

**Comment by frodrigo** [comment]
J'ai tout vérifié et relancé. Il n'y a pas d'erreur, mis ça ne remonte pas.

Les minute diff OSM-FR sont en retard. Je pense que c'est liée.
http://download.openstreetmap.fr/replication/europe/france/minute/state.txt
http://munin.openstreetmap.fr/osm14.openstreetmap.fr/download.vm.openstreetmap.fr/osm_replication_lag_osmbin.html

À suivre.

**Comment by frodrigo** [comment]
C'est bon, ça vient d'arriver.
