### ISSUE TITLE
Vente de Lumignons du Cœur à Lyon

### ISSUE THREAD

**Issue by overflorian** [caresteouvert/caresteouvert#854]
La mairie de Lyon nous demande de rajouter une case à cocher "Vente de Lumignons du Cœur" sur tous les POIs de la ville (périmètre exact : https://www.openstreetmap.org/relation/120965)

Lorsque la case est cochée, l'info à afficher est "Vente de Lumignons du Cœur"  avec un petite icône "information" sur laquelle il est possible de cliquer et qui afficherait le message "Achetez un lumignon à 2€ et soutenez l’association Les Petits Frères des Pauvres" + lien vers https://www.lyon.fr/actualite/solidarite/les-benefices-des-lumignons-du-coeur-aux-petits-freres-des-pauvres 

J'imaginais au début que cela soit spécifique au sous-domaine lyon.caresteouvert.fr mais au final, je pense qu'il n'y a pas de problème à impacter tout le service.

Icône pour le lumignon : https://thenounproject.com/search/?q=candle&i=405020
Icône pour le "i" information : https://github.com/caresteouvert/caresteouvert/blob/master/icons/info.svg

**Comment by vinber** [comment]
ok pour moi, on réfléchira au seul sous domaine plus tard !

**Comment by PanierAvide** [comment]
C'est implémenté (mais je ne sais pas si le déploiement automatique est activé ?), et ça affiche pour tous les POIs uniquement sur le domaine lyon.caresteouvert.fr

**Comment by frodrigo** [comment]
Déployement manuel, mais je vais le faire.

**Comment by PanierAvide** [comment]
Cool merci à toi :smile:

**Comment by frodrigo** [comment]
C'est en ligne

**Comment by vinber** [comment]
merci mais c'est surprenant non : https://lyon.caresteouvert.fr/@45.752227,4.842014,17.06/place/n2956398528
![Capture d’écran de 2020-11-20 06-02-18](https://user-images.githubusercontent.com/890869/99761284-00486d00-2af6-11eb-9f09-0d35cbfa1db3.png)

la partie Pas d'info, à vous de le dire, il en reste il en manque / c'est un reste des masques ou du gel non ?

**Comment by overflorian** [comment]
Oui, c'est le même principe que pour les masques/gel à l'époque. Je trouve que c'est une solution élégante, j'ai transmis à la communauté Lyonnaise pour voir ce s'ils se l'approprient :)

**Comment by vinber** [comment]
mais je ne comprends pas le sens de il en reste il n'y en a plus, c'est des achats en ligne

**Comment by vinber** [comment]
Comment se procurer un Lumignon du Cœur ?

Pour la première fois, et à partir du lundi 23 novembre, vous avez la possibilité d'acheter des lumignons en ligne. Pour chaque "e-lumignonsducoeur" virtuel acheté, un véritable lumignon sera posé à Lyon afin de réaliser une fresque monumentale le soir du 8 décembre ! Cet événement sera retransmis en live sur internet.

Pour les personnes qui le souhaitent : il sera également possible d'acheter un véritable lumignon dans un certain nombre de points physiques à Lyon (liste à venir).

**Comment by vinber** [comment]
Peut-être que le texte c'est plutôt : En vente ici / Pas de vente ici

**Comment by overflorian** [comment]
Oui tu as raison Vincent.
@PanierAvide je propose de changer tout simplement le wording pour OUI / NON

**Comment by PanierAvide** [comment]
Wording changé

**Comment by overflorian** [comment]
c'est pas en prod, @frodrigo doit faire une MAJ coté serveur, c'est ça ?

**Comment by frodrigo** [comment]
Voues êtes sur que ça marche quand on clique sur les boutons ?

**Comment by PanierAvide** [comment]
ça envoie au moins la requête au serveur, après est-ce que le backend conserve l'info et la réaffiche à la prochaine màj des données... à l'époque oui, maintenant je ne sais pas

**Comment by frodrigo** [comment]
En prod.

**Comment by overflorian** [comment]
Hey, petite évol complémentaire : peut-on rajouter un filtre "Lumignons" pour tous les POIs ?
![image](https://user-images.githubusercontent.com/11553211/100199353-5f92ec80-2efd-11eb-8cb2-6b51daf37290.png)
Je l'imagine juste à droite du filtre "livraison" mais une autre idée d'implémentation peut également convenir.

**Comment by PanierAvide** [comment]
Au final ce n'est pas si simple...
- Il faut modifier la structure en base de données pour `poi_osm_light` et `poi_osm_next` pour ajouter une colonne `lumignon` (sur le même modèle que les masques/gel)
- Utiliser la version ici de pg_featureserv au lieu de celle déployée sans quoi les filtres ne fonctionnent pas dans certains cas https://github.com/osmontrouge/pg_featureserv
- Et ajouter le bouton dans l'interface, mais une fois que les deux points au dessus sont faits, ça va

@frodrigo je peux modifier les scripts SQL en conséquence, ça ira pour le déploiement ? Et peux-tu déployer la version de pg_featureserv patchée ?

**Comment by frodrigo** [comment]
> @frodrigo je peux modifier les scripts SQL en conséquence, ça ira pour le déploiement ? Et peux-tu déployer la version de pg_featureserv patchée ?

Ok tu fais le SQL. On fera le docker pour la version patché.

**Comment by PanierAvide** [comment]
Je viens de pousser ça, le SQL et le code côté client

**Comment by frodrigo** [comment]
La partie SQL est passé avec la mise à jour auto.
Pour pg_featureserv on fait ça lundi.

**Comment by frodrigo** [comment]
@PanierAvide la version patché de pg_featureserv est en place. Tu peux confirmer que ça fait bien ce qu'il faut ?

**Comment by PanierAvide** [comment]
J'ai "échec de la connexion sécurisée", exemple https://features.caresteouvert.fr/collections/public.poi_osm/items?limit=10&offset=0&bbox=4.8223982269526005%2C45.77066604818606%2C4.842409571219889%2C45.76482813754217&normalized_cat=food&orderBy=status_order&lumignon=yes%2Conly

**Comment by frodrigo** [comment]
> J'ai "échec de la connexion sécurisée", exemple https://features.caresteouvert.fr/collections/public.poi_osm/items?limit=10&offset=0&bbox=4.8223982269526005%2C45.77066604818606%2C4.842409571219889%2C45.76482813754217&normalized_cat=food&orderBy=status_order&lumignon=yes%2Conly

Pour l'nstant j'ai fait marche arrière, je ne sais pas ce qu'il c'est passé.

**Comment by frodrigo** [comment]
@PanierAvide cette fois c'est bon.

**Comment by PanierAvide** [comment]
C'est OK en l'état, ça fonctionne comme attendu. Merci :wink:
