### ISSUE TITLE
Cibler les collectivités locales

### ISSUE THREAD

**Issue by overflorian** [caresteouvert/caresteouvert#855]
# Ciblons les collectivités locales.

Aujourd'hui un message pour les gestionnaires de franchises s'affiche uniquement sur les franchises :
Exemple :
![image](https://user-images.githubusercontent.com/11553211/99697733-4a970300-2a90-11eb-90b9-29553f41cf49.png)
https://lyon.caresteouvert.fr/@45.752194,4.844121,16.86/place/n249718449

 ## A faire :
- [x] Supprimer ce message existant
- [ ] Sur tous les POIs, ajouter le message :
> **Collectivités : soutenez les commerces de votre territoire**
> Solution de promotion durant la crise sanitaire

Un clic sur ce message renvoit vers un popup :
- [x] Créer un popup avec le message :
> **Collectivités**
> Vous êtes une collectivité locale, une CCI, un office de tourisme ... et vous cherchez une solution concrète pour soutenir vos commerces de proximité ?
> "Ça Reste Ouvert" est la solution de communication de crise qu'il vous faut.

> Le service permet aux citoyens confinés de trouver les lieux ouverts, leurs horaires d'ouverture et conditions d'accès (dont la livraison et le click & collect) et bien plus encore.

> [INSÉRER ICI LE TABLEAU DE PRICING] (à venir)

Bouton [CONTACTEZ NOUS] qui renvoit vers le formulaire :
- [X] Créer le formulaire pour récupérer les leads : https://airtable.com/shrFEO8LAYHsMMXKD

**Comment by nlehuby** [comment]
À noter que le formulaire de contact actuel est aussi proposé dans la popup "Commerce manquant ?" : "Vous avez votre propre établissement et vous avez besoin d'aide pour le rajouter "

**Comment by frodrigo** [comment]
Il faudrait plutôt faire un second formulaire, non ?

**Comment by frodrigo** [comment]
> "Ça Reste Ouvert" est la solution de communication de crise qu'il vous faut.

Ça fait très promotion des années 50.

**Comment by frodrigo** [comment]
> Il faudrait plutôt faire un second formulaire, non ?

Il y a bien déjà un autre formulaire pour ça.

**Comment by frodrigo** [comment]
C'est fait et déployé.

Mais je n'ai pas su le généraliser à tous les POI cc @PanierAvide ?

**Comment by overflorian** [comment]
Voici le tableau à insérer dans le popup :
![tarifs](https://user-images.githubusercontent.com/11553211/99879652-8526aa00-2c0e-11eb-993b-7a51ac55e575.png)

La plaquette quand à elle est dispo à l'adresse https://blog.caresteouvert.fr/plaquette

**Comment by overflorian** [comment]
@frodrigo indique le message suivant ne s'affiche pas sur TOUS les POIs :
![image](https://user-images.githubusercontent.com/11553211/100374582-c9e68280-300c-11eb-9e63-eac188cd43db.png)
@PanierAvide peux-tu stp regarder ça ?

De mon coté je vais créer une landing page sur le blog pour insérer le tableau des tarifs et @frodrigo l'intégrera.

**Comment by PanierAvide** [comment]
C'est modifié

**Comment by overflorian** [comment]
Merci. De mon coté j'ai terminé la landing page ici : https://blog.caresteouvert.fr/soutenez-vos-commerces-de-proximite
@frodrigo tu peux créer le lien vers cet URL depuis le message ?

**Comment by frodrigo** [comment]
On avait dit en direct, ou depuis la popup ?

**Comment by overflorian** [comment]
en direct

**Comment by vinber** [comment]
en direct dans un autre onglet ?

**Comment by overflorian** [comment]
je pense que c'est la meilleure solution oui

**Comment by frodrigo** [comment]
J'ai fait la modif. C'est en ligne.
Mais j'ai fait ça comme j'ai pu, ce n'est pas super propre.

**Comment by overflorian** [comment]
ça passe ;)
merci
