### ISSUE TITLE
Afficher les bars et cafés

### ISSUE THREAD

**Issue by vinber** [caresteouvert/caresteouvert#857]
Report d'un échange par messagerie osm :+1: 

les bars et cafés sont censés être fermés. … mais ils sont ouverts. Que le café fasse PMU, Qu’il fasse de la vente à emporter soit …

Je pense qu’il est plus judicieux de mettre café et bar sur “careste ouvert” et par défaut de les positionner en fermés. … Les coiffeurs sont bien présents et sont tous fermés.

Merci @DF45

Exemple ce bar https://www.openstreetmap.org/node/2792084830#map=19/44.77436/-0.34871

n'est pas visible https://www.caresteouvert.fr/@44.774522,-0.348818,19.05

**Comment by vinber** [comment]
je ne comprends pas pourquoi sur ces objets, les restaurants sont visibles, pas les café, à quel endroit cela se joue ?
![Capture d’écran de 2020-11-20 13-10-32](https://user-images.githubusercontent.com/890869/99798788-e0369f00-2b31-11eb-8828-d151013a550c.png)

**Comment by overflorian** [comment]
Est-ce que cette suggestion tient toujours après l'annonce présidentielle ? Je ne pense pas.

**Comment by overflorian** [comment]
Les récentes évolutions rendent, je pense, ce bug obsolète; je le ferme.
