### ISSUE TITLE
Intégrer l'option "Y compris hors crise" dans les précisions

### ISSUE THREAD

**Issue by gileri** [caresteouvert/caresteouvert#859]
**Is your feature request related to a problem? Please describe.**
J'ai vu des drive_through:covid19=yes ajouté sur des commerces proposant le drive en permanence, alors que le tag drive_through=yes n'était pas apposé. Idem pour la livraison.

**Describe the solution you'd like**
Ajouter l'option "Y compris hors crise" dans la liste "Oui/Non/Je sais pas" pour le drive, vente à emporter, livraison. Si "Y compris hors crise" est sélectionné, apposer le tag `delivery/drive_through/takeaway=yes` sans suffixe `:covid19`, et retirer la version suffixée `:covid19` du tag.

**Describe alternatives you've considered**
Retirer complètement le suffixe `covid19`. La "crise" s'éternise; et même si elle se terminait bientôt, je pense que beaucoup de commerçants continueraint à proposer ces services une fois mis en place.

**Comment by overflorian** [comment]
Avec le nouveau formulaire que nous avons mis en ligne, les tags delivery classiques (c'est à dire non liés au covid) sont utilisés. Je crois que cela résout le problème, je ferme donc ce bug

**Comment by gileri** [comment]
Oui génial merci pour le boulot !
