### ISSUE TITLE
Category change: Distributeur à pain (vending machine bread)

### ISSUE THREAD

**Issue by MatthieuOSM** [caresteouvert/caresteouvert#861]
Bonjour,

`amenity=vending_machine`
`vending=bread`

De la même façon que les distributeurs de pizza ([#333](https://github.com/caresteouvert/caresteouvert/issues/333)), peut-on faire la distinction entre boulangerie et distributeur de pain ? (qui peut distribuer des viennoiseries également mais c'est un détail)

Cela me semble important, j'ai en tête 4 petites communes autour de chez moi en milieu rural où les distributeurs sont à disposition (en complément des livraisons) sans quoi il faut se déplacer sur des communes mieux fournies.

Exemple : https://www.caresteouvert.fr/food@45.642908,-0.063741,17.95/place/n8069999606

**Comment by PanierAvide** [comment]
Done, see #870
