### ISSUE TITLE
access:covid19 et "accueil physique" très perturbants

### ISSUE THREAD

**Issue by nuxper** [caresteouvert/caresteouvert#862]
Je pense que cela vaut un ticket séparé

La notion de (access:covid19=oui/non) ne semble pas clair pour le cas du click and collect seul:
Je donne un exemple : https://www.openstreetmap.org/note/2425133 : le magasin ne propose pas de vente sur place, uniquement du click and collect
il a pourtant indiqué : Ce lieu propose un accueil physique sur place = Oui
Si je suis bien la page https://wiki.openstreetmap.org/wiki/FR:Covid-19_-_how_to_map , access:covid19 devrait être "false".

Cette notion de "propose un accueil physique" pour un magasin proposant uniquement du click and collect peut être interprété de manière différente.

En mode consultation, le message est également très perturbant:
![image](https://user-images.githubusercontent.com/7891262/99877960-2b1fe780-2c02-11eb-8a77-e4916c573105.png)
Le message indique "Pas d'accueil physique sur place" alors que le magasin est ouvert de 10:00 à 19:00 du mardi au samedi pour le retrait des commandes.

autres notes : https://www.openstreetmap.org/node/3607198523 , https://www.openstreetmap.org/node/6912880084 , https://www.openstreetmap.org/node/7343441571, https://www.caresteouvert.fr/@45.748578,4.881469,18.14/place/n8147283479

**Comment by vinber** [comment]
>  il a pourtant indiqué : Ce lieu propose un accueil physique sur place = Oui

"Ce lieu propose l'accueil habituel sur place" serait plus approprié ?

et il s'est peutêtre trompé et faire une bascule du access:covid19=no ?

**Comment by vinber** [comment]
> Le message indique "Pas d'accueil physique sur place"

"L'accueil physique habituel n'est pas possible" serait plus approprié / il faut rester "souple" et surtout que les gens à la fois osent commander, téléphoner, ...

**Comment by nuxper** [comment]
Si j'ai bien compris l'idée, la description exacte serait "Ce lieu propose un accueil physique sans rendez-vous et sans commande préalable" mais c'est bien compliqué. Je dois admettre que je n'ai jamais été fan de ce tag car justement je le trouve difficile à appréhender, mais c'est personnel.

Je trouve ta proposition "L'accueil physique habituel n'est pas possible" vs "Accueil physique comme habituellement" mieux même si je crois que ça ne couvrira pas tous les cas:
- Pour un magasin qui vent des biens 
      A1 -> qui normalement les propose en libre service mais ne peut proposer que du click and collect, type librairie: (access:covid19=no) "L'accueil physique habituel n'est pas possible": **OK**
      A2 -> qui propose le libre service comme d'habitude, type magasin informatique : "Accueil physique comme habituellement" : **OK**
      A3 -> qui livre uniquement: "L'accueil physique habituel n'est pas possible": **Ne porte pas vraiment l'information voulue : on n'indique pas qu'il n'y a pas d'accueil sur place**
- Pour un resto type fast food qui proposait la commande sur place à emporter et la consommation sur place (kebab...) et ne propose plus que la commande sur place à emporter:
      B1 ->"Accueil physique comme habituellement" : **Embettant** (access:covid19=yes puisqu'on y est accueilli sans rendez-vous)
- Pour un resto avec consommation faisant désormais du click and collect uniquement, "L'accueil physique habituel n'est pas possible" : **OK**
- Pour un service type mairie qui accueille toujours du publique: "Accueil physique comme habituellement" : **OK**
- Pour un coiffeur qui pourrait rendre la réseravation obligatoire "L'accueil physique habituel n'est pas possible" : **pas idéal mais j'imagine qu'il faudra un autre tag**

Je n'ai malheureusement pas de proposition idéale ceci dit.

**Comment by overflorian** [comment]
Hello, je partage de constat qu'il y a un problème; voici ma proposition pour le résoudre : https://github.com/caresteouvert/caresteouvert/issues/841

**Comment by overflorian** [comment]
On a mis en ligne un nouveau formulaire qui essaye de prendre en compte ces problèmes. Je ferme donc ce bug.
