### ISSUE TITLE
Un point ne s'actualise plus

### ISSUE THREAD

**Issue by vinber** [caresteouvert/caresteouvert#863]
Ce point dans CRO (https://www.caresteouvert.fr/@44.836567,-0.571648,16.98/place/n3953660273) n'est pas synchronisé une heure après sa mise à jour : https://www.openstreetmap.org/node/3953660273

opening_hours:covid19=Mo-Su 16:00-18:00 devrait à minima le faire apparaitre ouvert ?

Signaler un changement n'est plus accessible.

**Comment by frodrigo** [comment]
Idem #862
http://munin.openstreetmap.fr/osm14.openstreetmap.fr/download.vm.openstreetmap.fr/osm_replication_lag_osmbin.html

**Comment by vinber** [comment]
le lien munin c'est pour dire que la base explose ?

**Comment by jocelynj** [comment]
Si CRO utilise les diffs de download.openstreetmap.fr, c'est "normal" d'avoir des diffs générés avec un peu de délai, allant jusqu'à quelques heures. Ça arrive quand un diff modifie des grosses relations, et qu'on doit vérifier si les modifications sont à propager dans les sous-diffs. Il faut attendre un peu pour que ça soit à jour.

**Comment by frodrigo** [comment]
@vinber non c'est le retard des diff minute de osm-fr

Le bon lien est d'ailleurs celui-là
http://munin.openstreetmap.fr/osm12.openstreetmap.fr/osm108.openstreetmap.fr/osm_replication_lag_osmbin.html
L'autre n'est pas encore en prod

**Comment by vinber** [comment]
ok, ce qui me surprend sur ce point c'est que je l'ai vu passer vert sur CRO, puis revenir gris ! (même peut-être que c'était juste un effet du navigateur, je ne suis plus sur); Donc wait and see !

**Comment by vinber** [comment]
c'est ok, il est à jour
