### ISSUE TITLE
Missing category: household linen ( linge de maison )

### ISSUE THREAD

**Issue by nuxper** [caresteouvert/caresteouvert#864]
**Name**: linge de maison

**Tagging**: shop=household_linen

https://wiki.openstreetmap.org/wiki/FR:Tag:shop%3Dhousehold_linen

**Country**: France

**Example in OpenStreetMap** : https://www.openstreetmap.org/node/6920636806

**Example in "Ca reste ouvert"**: https://www.caresteouvert.fr/@45.759399,4.834619,21.22

**Icon**: pas d'icone sur osm-carto désolé

**Comment by PanierAvide** [comment]
Done, see #870
