### ISSUE TITLE
Missing category: (name of category)

### ISSUE THREAD

**Issue by vmarino-69** [caresteouvert/caresteouvert#868]
**Name**: (name of category)

Pas sur la carte : situé 9 rue Dumont d'Urville
**Tagging**: (tagging of category)

**Country**: (country of category)

**Example in OpenStreetMap**: (link starting with https://www.openstreetmap.org/node/...)

**Example in "Ca reste ouvert"**: (link starting with https://www.caresteouvert.fr/...)

**Icon**: (link starting with https://github.com/gravitystorm/openstreetmap-carto/blob/master/symbols/...)
https://zibibbo-restaurant.eatbu.com/?lang=fr

**Comment by overflorian** [comment]
Bonjour @vmarino-69, quelle est la demande ? je ne suis pas certain de comprendre, peux-tu stp préciser ?

**Comment by vmarino-69** [comment]
Bonjour, j'ai peut-être mal effectué ma demande. Je souhaitais pouvoir être réferencé sur la carte des commerces.
Restaurant ZIBIBBO - situé 9 rue Dumont d'Urville à Lyon 4eme
https://zibibbo-restaurant.eatbu.com/?lang=fr

Appelez moi si besoin 06 28 78 04 33

________________________________
De : Overflorian <notifications@github.com>
Envoyé : mercredi 25 novembre 2020 09:32
À : caresteouvert/caresteouvert <caresteouvert@noreply.github.com>
Cc : vmarino-69 <vmarino@hotmail.fr>; Mention <mention@noreply.github.com>
Objet : Re: [caresteouvert/caresteouvert] Missing category: (name of category) (#868)


Bonjour @vmarino-69<https://github.com/vmarino-69>, quelle est la demande ? je ne suis pas certain de comprendre, peux-tu stp préciser ?

**Comment by overflorian** [comment]
Bonjour, il n'y a pas de mal. Je vais faire cela.
Est-ce que votre établissement est situé à coté du restaurant "le cousu" ?
https://www.caresteouvert.fr/@45.777777,4.836016,19.19/place/n6864720610
Mais peut-être le remplace-t-il ?

**Comment by vmarino-69** [comment]
Merci!
Pour vous répondre : oui, le COUSU est situé rue du charriot d'or - une rue perpendiculaire à la rue Dumont d'Urville.
Ce sont bien 2 adresses différentes.
Le restaurant Zibibbo ne remplace pas le Cousu.
________________________________
De : Overflorian <notifications@github.com>
Envoyé : mercredi 25 novembre 2020 11:16
À : caresteouvert/caresteouvert <caresteouvert@noreply.github.com>
Cc : vmarino-69 <vmarino@hotmail.fr>; Mention <mention@noreply.github.com>
Objet : Re: [caresteouvert/caresteouvert] Missing category: (name of category) (#868)


Bonjour, il n'y a pas de mal. Je vais faire cela.
Est-ce que votre établissement est situé à coté du restaurant "le cousu" ?
https://www.caresteouvert.fr/@45.777777,4.836016,19.19/place/n6864720610
Mais peut-être le remplace-t-il ?

**Comment by overflorian** [comment]
J'ai créé votre établissement sur la carte : https://www.caresteouvert.fr/@45.777729,4.835884,19.19/place/n8164212513
libre à vous de vérifier que j'ai bien donné les bonnes infos et de les corriger au besoin.
Si besoin, nous avons écrit un guide pour vous y aider : https://blog.caresteouvert.fr/que-faire-sil-manque-un-commerce-dans-ca-reste-ouvert/
Cordialement

**Comment by vmarino-69** [comment]
Merci infiniment ! Le 25 nov. 2020 13:32, Overflorian <notifications@github.com> a écrit :
Closed #868.

**Comment by vmarino-69** [comment]
C'est parfait ! Je n'ai pas vu de modifications à apporter. Merci beaucoup !Le 25 nov. 2020 13:32, Overflorian <notifications@github.com> a écrit :

J'ai créé votre établissement sur la carte : https://www.caresteouvert.fr/@45.777729,4.835884,19.19/place/n8164212513

libre à vous de vérifier que j'ai bien donné les bonnes infos et de les corriger au besoin.

Si besoin, nous avons écrit un guide pour vous y aider : https://blog.caresteouvert.fr/que-faire-sil-manque-un-commerce-dans-ca-reste-ouvert/

Cordialement
