### ISSUE TITLE
Ouvrir le formulaire en grand écran sur mobile

### ISSUE THREAD

**Issue by overflorian** [caresteouvert/caresteouvert#869]
Lorsque l'on clique sur "signaler un changement", le volet devrait s'ouvrir en plein écran.

## Comportement actuel
<img width=50% src="https://user-images.githubusercontent.com/11553211/100224122-b0660d80-2f1c-11eb-9adb-88343d35acc5.png">

## Problème à résoudre
1. focaliser l'attention de l'utilisateur et ne pas polluer avec la carte.
2. on voit que le formulaire d'édition n'apparaît pas dans l'écran, obligeant l'utilisateur à scroller en dessous de la ligne de flottaison pour voir les CTA

## Comportement proposé
l'écran est maximisé par défaut lorsque le bouton est cliqué

**Comment by PanierAvide** [comment]
C'est fait, ce sera déployé en même temps que le nouveau formulaire.
