### ISSUE TITLE
Faire le tri dans les POIs

### ISSUE THREAD

**Issue by overflorian** [caresteouvert/caresteouvert#870]
Ce second confinement est bien différent du premier.
Recentrons-nous sur le besoin du citoyen durant cette nouvelle phase de crise sanitaire.
Je propose (liste non-exhaustive et suivant les recommandations déjà faite par les GC (gentils contributeurs) :

# Types de POI à ajouter
- ajouter `shop=household_linen` dans la catégorie "boutiques" cf. https://github.com/caresteouvert/caresteouvert/issues/864 ([195 occurrences](https://taginfo.openstreetmap.fr/tags/?key=shop&value=household_linen#overview) en France, c'est plus que ce que je pensais)
- ajouter `vending=bread` dans la catégorie "restauration" ; sous-catégorie "distributeur automatique" cf. https://github.com/caresteouvert/caresteouvert/issues/861 ([219 occurences](https://taginfo.openstreetmap.fr/search?q=vending%3Dbread), pas trop mal)
- ajouter les `shop=wine` dans la catégorie "alimentation" cf. https://github.com/caresteouvert/caresteouvert/issues/840
- ajouter les `craft=distillery` dans la catégorie "alimentation" cf. https://github.com/caresteouvert/caresteouvert/issues/750
- ajouter `craft=shoemaker` dans la catégorie "boutiques" cf.  https://github.com/caresteouvert/caresteouvert/issues/799
- ajouter `craft=key_cutter` dans la catégorie "services pratiques" cf. https://github.com/caresteouvert/caresteouvert/issues/797
- ajouter plein de lieux liés à la santé cf. https://github.com/caresteouvert/caresteouvert/issues/12 dont au moins :
  - healthcare=doctor
  - healthcare=laboratory
  - healthcare=nurse cf. https://github.com/caresteouvert/caresteouvert/issues/199

# Types de POI à virer
- virer les `amenity=public_bookcase` cf. https://github.com/caresteouvert/caresteouvert/issues/860
- virer les `amenity=atm` cf. https://github.com/caresteouvert/caresteouvert/issues/837
- virer les `health=condoms`
- virer les `mobility=public_transport_tickets`

**Comment by PanierAvide** [comment]
Fait, à déployer @frodrigo

**Comment by frodrigo** [comment]
C'est automatique maintement. Sous 5min.

**Comment by PanierAvide** [comment]
Ça c'est cool, merci :smiley:
