### ISSUE TITLE
Autocomplétion : impossible de trouver un lieu

### ISSUE THREAD

**Issue by rouelibre1** [caresteouvert/caresteouvert#873]
**Describe the bug**
L'autocomplétion trouve le lieu mais remplace par une liste de suggestions bien plus loin de la géoloc. C'est trop frustrant !

**To Reproduce**
1. Ouvrir CRO web, centré sur Strasbourg
2. Saisir "Au petit artisan, Strasbourg"
3. Au cours de la saisie le lieu s'affiche furtivement mais il est remplacé par une liste de suggestions plus lointaines.

**Screenshots**
Vidéo https://www.awesomescreenshot.com/video/1918961?key=27d8ddaf5b3ca79a1fa1695bf72af727

**Desktop (please complete the following information):**
 - OS: Win 10
 - Browser Firefox
 - Version 83.0

**Comment by overflorian** [comment]
En effet, c'est un problème. Ça rejoint nos réflexions en cours https://github.com/caresteouvert/caresteouvert/issues/865
Je pense qu'il faut configurer le géocodeur pour prioriser les lieux en fonction de la proximité de la position de l'utilisateur et supprimer tous les POIs hors France et territoires d'outre-mer.
Je crois que @PanierAvide avait aussi déjà priorisé les POIs affichés dans la bbox actuelle.
@frodrigo qu'en penses-tu ? D'autres solutions auxquelles je n'aurai pas pensé ?

**Comment by frodrigo** [comment]
J'ai modifié la configuration du géocodage, qui autorisé des résultats dans tous les pays ouverts précédemment, pour le relimiter à la France. C'est juste moins pire.

Il y a une option dans l'API Jawgs pour prioriser par proximité, il faudrait aussi l'ajouter
```
focus.point.lat=-33.856680&focus.point.lon=151.215281
```

Mais tout ça ne résoud pas le problème de fond.

**Comment by overflorian** [comment]
C'est déjà un premier pas dans la bonne direction, merci

**Comment by rouelibre1** [comment]
Je viens de découvrir http://demo.addok.xyz, ça pulse ! Mais vous connaissez / utilisez peut-être déjà ?

**Comment by overflorian** [comment]
Oui on connaît et oui c'est intéressant. A l'occasion on l'utilisera ;)
Je ferme ce bug dans l'immédiat.
