### ISSUE TITLE
changement de wording et de couleurs

### ISSUE THREAD

**Issue by overflorian** [caresteouvert/caresteouvert#874]
Changements sur la carte (temporaire en attendant le 15 janvier) :
- [x] On passe les lieux actuellement gris en vert (sauf restaurants et bars).
- [x] Sur les lieux en **vert**, on supprime la mention "Lieu ouvert durant la crise sanitaire".
- [ ] Sur les lieux en **vert**, changer le wording du bouton "signaler un changement" par "compléter"
- [x] Sur les lieux en **gris** (uniquement restaurants et bars), on ne change rien
- [x] Sur les lieux en **rouge**, on remplace "Lieu fermé durant la crise sanitaire" par "Lieu temporairement fermé durant la crise sanitaire"

**Comment by frodrigo** [comment]
J'ai fait le premier point dans une PR, pour avoir la relecture de @PanierAvide.
@vinber Il faut déclarer explicitement les catégories légalement pleinement ouvertes. Seule les ‘open’ sont pris en compte en plus des ‘close’.

**Comment by vinber** [comment]
donc dans legal_rules j'ai 
- tout mis en open
- sauf la categorie eat en partial (après une petite erreur, tous les restaurants sont passés rouge, désolé !)

et en closed 
- cinema | [{"amenity":"cinema"}]
- community_centre | [{"amenity":"community_centre"}]
- sports_centre | [ { "leisure": "sports_centre\|fitness_centre" } ]
- theatre | [ { "amenity": "theatre" } ]

**Comment by frodrigo** [comment]
> Sur les lieux en vert, on supprime la mention "Lieu ouvert durant la crise sanitaire". Changer le wording du bouton "signaler un changement" par "compléter"

On remplace "signaler un changement" par "compléter" que sur les lieux ouverts ? Pour l’instant c'est le même libellé quel que soit le statut.

**Comment by overflorian** [comment]
C'est ce que nous avions décidé oui. Mais peut-être as-tu une meilleure idée @frodrigo ?
