### ISSUE TITLE
Add Plausible analytic

### ISSUE THREAD

**Issue by frodrigo** [caresteouvert/caresteouvert#876]
Add Plausible analytic.

There is a `vue-plausible` module. http://vuejscomponent.com/vue-plausible

configurable with
```js
    ['vue-plausible', {
      domain: 'caresteouvert.fr'
    }]
```

But if fails with (on server side I guess)
```
history is not defined
```

@PanierAvide help!

**Comment by PanierAvide** [comment]
Pushed a commit which seems to make it work, if you can check on Plausible if any data is coming in. Note that stats are sent only if user consent to tracking (see RGPD banner).

**Comment by frodrigo** [comment]
C'est déployé, mais je ne vois pas passer les requêtes vers plausible.

**Comment by PanierAvide** [comment]
De mon côté je les vois dans le navigateur, il faut cliquer sur une catégorie ou POI par exemple. Et surtout avoir autorisé les cookies et ne pas avoir le "do not track" activé.

**Comment by overflorian** [comment]
c'est bon j'ai bien les stats qui arrivent sur plausible. merci :)
