### ISSUE TITLE
Nouvelles version d'objets OSM sans modifications

### ISSUE THREAD

**Issue by gileri** [caresteouvert/caresteouvert#878]
**Describe the bug**
Des objets ont des nouvelles version envoyées, alors qu'il n'y a pas de changements. 
[Example](https://osmlab.github.io/osm-deep-history/#/node/1831952591)

**To Reproduce**
Je sais pas malheureusement.

**Expected behavior**
Ne créer de nouvelle version d'objet OSM que lorsqu'il y a une modification à appliquer

**Comment by vinber** [comment]
J'en ai un sous le coude aussi : https://osmlab.github.io/osm-deep-history/#/node/5248486521

**Comment by PanierAvide** [comment]
Ça devrait être corrigé par https://github.com/caresteouvert/caresteouvert_backend/commit/209e63b94b04604965cbf9127222ccfdf24fbda7

@frodrigo tu m'avais dit que le déploiement était automatique pour le front, c'est aussi le cas pour le backend ?

**Comment by frodrigo** [comment]
> Ça devrait être corrigé par [caresteouvert/caresteouvert_backend@209e63b](https://github.com/caresteouvert/caresteouvert_backend/commit/209e63b94b04604965cbf9127222ccfdf24fbda7)
> 
> @frodrigo tu m'avais dit que le déploiement était automatique pour le front, c'est aussi le cas pour le backend ?

Je viens de voir qu'un commit sur le backend ne déclenche pas de mise à jour automatique. Par contre les changements sur caresteouvert/caresteouvert rebuilde et déploient de backend.

**Comment by gileri** [comment]
Du coup je ferme, si j'ai compris le correctif est déployé. Merci !
