### ISSUE TITLE
"Publier" stays grayed out after "Vente à emporter" is enabled

### ISSUE THREAD

**Issue by nuxper** [caresteouvert/caresteouvert#881]
**Describe the bug**
On a restaurant when I activate "Vente à emporter", I can't press "Publier"
The behavior is the same if I just click on "Livraison à domicile"

**To Reproduce**
1. Go to https://www.caresteouvert.fr/eat@45.759563,4.830182,17.34
![image](https://user-images.githubusercontent.com/7891262/102197683-c2a2ee00-3ec1-11eb-8b10-3a86ef7e3bad.png)

2. Click "La Voûte Chez Léa"
![image](https://user-images.githubusercontent.com/7891262/102197748-dbab9f00-3ec1-11eb-8da3-bdf5f50100fc.png)

3. Click on 'Signaler un Changement'
![image](https://user-images.githubusercontent.com/7891262/102197977-1f060d80-3ec2-11eb-8252-2a0219963290.png)

Note : "Click & Collect" is enabled but "Livraison à domicile" and "Vente à emporter" are disabled initially

4. Click on 'Vente à emporter'
![image](https://user-images.githubusercontent.com/7891262/102198183-6096b880-3ec2-11eb-8ffb-6f4385a1e088.png)

5. See error : "Publier" stays grayed out

**Expected behavior**
When toggling on "Vente à emporter", "Publier" becomes available.

**Screenshots**
See above

**Desktop (please complete the following information):**
 - OS: ubuntu
 - Browser firefox
 - Version 83.0 (64-bit)

**Smartphone (please complete the following information):**
 - Not tested

**Additional context**
Initial covid19 tags:
 - access:covid19 : yes
 - drive_through:covid19 : yes
 - opening_hours:covid19 : open

**Comment by PanierAvide** [comment]
Thanks for the feedback, this issue is solved and website should be updated in a few minutes.
